// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByAction = `-- name: CountAuditLogsByAction :one
SELECT COUNT(*) FROM audit_logs WHERE action = $1
`

func (q *Queries) CountAuditLogsByAction(ctx context.Context, action string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByAction, action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByUserID = `-- name: CountAuditLogsByUserID :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1
`

func (q *Queries) CountAuditLogsByUserID(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, details, ip_address, created_at)
VALUES ($1, $2, $3, $4, NOW())
`

type CreateAuditLogParams struct {
	UserID    pgtype.Int8 `json:"user_id"`
	Action    string      `json:"action"`
	Details   []byte      `json:"details"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const deleteAuditLogsOlderThan = `-- name: DeleteAuditLogsOlderThan :execrows
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) DeleteAuditLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestAuditLogByUserAndAction = `-- name: GetLatestAuditLogByUserAndAction :one
SELECT id, user_id, action, details, ip_address, created_at
FROM audit_logs WHERE user_id = $1 AND action = $2
ORDER BY created_at DESC LIMIT 1
`

type GetLatestAuditLogByUserAndActionParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Action string      `json:"action"`
}

func (q *Queries) GetLatestAuditLogByUserAndAction(ctx context.Context, arg GetLatestAuditLogByUserAndActionParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLatestAuditLogByUserAndAction, arg.UserID, arg.Action)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, details, ip_address, created_at
FROM audit_logs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, user_id, action, details, ip_address, created_at
FROM audit_logs WHERE action = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUserID = `-- name: ListAuditLogsByUserID :many
SELECT id, user_id, action, details, ip_address, created_at
FROM audit_logs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserIDParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByUserID(ctx context.Context, arg ListAuditLogsByUserIDParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
