// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bundles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBundlesByUserID = `-- name: CountBundlesByUserID :one
SELECT COUNT(*) FROM user_bundles WHERE user_id = $1
`

func (q *Queries) CountBundlesByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBundlesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBundle = `-- name: CreateBundle :one
INSERT INTO user_bundles (user_id, name, type, local_port, subdomain, remote_port, auto_connect, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, created_at, updated_at
`

type CreateBundleParams struct {
	UserID      int64       `json:"user_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	LocalPort   int32       `json:"local_port"`
	Subdomain   pgtype.Text `json:"subdomain"`
	RemotePort  pgtype.Int4 `json:"remote_port"`
	AutoConnect bool        `json:"auto_connect"`
}

type CreateBundleRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBundle(ctx context.Context, arg CreateBundleParams) (CreateBundleRow, error) {
	row := q.db.QueryRow(ctx, createBundle,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.LocalPort,
		arg.Subdomain,
		arg.RemotePort,
		arg.AutoConnect,
	)
	var i CreateBundleRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteAllBundles = `-- name: DeleteAllBundles :exec
DELETE FROM user_bundles WHERE user_id = $1
`

func (q *Queries) DeleteAllBundles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllBundles, userID)
	return err
}

const deleteBundle = `-- name: DeleteBundle :exec
DELETE FROM user_bundles WHERE id = $1 AND user_id = $2
`

type DeleteBundleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBundle(ctx context.Context, arg DeleteBundleParams) error {
	_, err := q.db.Exec(ctx, deleteBundle, arg.ID, arg.UserID)
	return err
}

const deleteBundleByName = `-- name: DeleteBundleByName :exec
DELETE FROM user_bundles WHERE user_id = $1 AND name = $2
`

type DeleteBundleByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteBundleByName(ctx context.Context, arg DeleteBundleByNameParams) error {
	_, err := q.db.Exec(ctx, deleteBundleByName, arg.UserID, arg.Name)
	return err
}

const getBundleByID = `-- name: GetBundleByID :one
SELECT id, user_id, name, type, local_port, subdomain, remote_port, auto_connect, created_at, updated_at
FROM user_bundles WHERE id = $1 AND user_id = $2
`

type GetBundleByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetBundleByID(ctx context.Context, arg GetBundleByIDParams) (UserBundle, error) {
	row := q.db.QueryRow(ctx, getBundleByID, arg.ID, arg.UserID)
	var i UserBundle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.LocalPort,
		&i.Subdomain,
		&i.RemotePort,
		&i.AutoConnect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBundleByName = `-- name: GetBundleByName :one
SELECT id, user_id, name, type, local_port, subdomain, remote_port, auto_connect, created_at, updated_at
FROM user_bundles WHERE user_id = $1 AND name = $2
`

type GetBundleByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetBundleByName(ctx context.Context, arg GetBundleByNameParams) (UserBundle, error) {
	row := q.db.QueryRow(ctx, getBundleByName, arg.UserID, arg.Name)
	var i UserBundle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.LocalPort,
		&i.Subdomain,
		&i.RemotePort,
		&i.AutoConnect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBundlesByUserID = `-- name: ListBundlesByUserID :many
SELECT id, user_id, name, type, local_port, subdomain, remote_port, auto_connect, created_at, updated_at
FROM user_bundles WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListBundlesByUserID(ctx context.Context, userID int64) ([]UserBundle, error) {
	rows, err := q.db.Query(ctx, listBundlesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBundle{}
	for rows.Next() {
		var i UserBundle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.LocalPort,
			&i.Subdomain,
			&i.RemotePort,
			&i.AutoConnect,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBundle = `-- name: UpdateBundle :exec
UPDATE user_bundles SET name = $3, type = $4, local_port = $5, subdomain = $6, remote_port = $7, auto_connect = $8, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateBundleParams struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	LocalPort   int32       `json:"local_port"`
	Subdomain   pgtype.Text `json:"subdomain"`
	RemotePort  pgtype.Int4 `json:"remote_port"`
	AutoConnect bool        `json:"auto_connect"`
}

func (q *Queries) UpdateBundle(ctx context.Context, arg UpdateBundleParams) error {
	_, err := q.db.Exec(ctx, updateBundle,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.LocalPort,
		arg.Subdomain,
		arg.RemotePort,
		arg.AutoConnect,
	)
	return err
}

const upsertBundle = `-- name: UpsertBundle :one
INSERT INTO user_bundles (user_id, name, type, local_port, subdomain, remote_port, auto_connect, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, name) DO UPDATE SET
    type = EXCLUDED.type,
    local_port = EXCLUDED.local_port,
    subdomain = EXCLUDED.subdomain,
    remote_port = EXCLUDED.remote_port,
    auto_connect = EXCLUDED.auto_connect,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > user_bundles.updated_at
RETURNING id, created_at, updated_at
`

type UpsertBundleParams struct {
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	LocalPort   int32              `json:"local_port"`
	Subdomain   pgtype.Text        `json:"subdomain"`
	RemotePort  pgtype.Int4        `json:"remote_port"`
	AutoConnect bool               `json:"auto_connect"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UpsertBundleRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertBundle(ctx context.Context, arg UpsertBundleParams) (UpsertBundleRow, error) {
	row := q.db.QueryRow(ctx, upsertBundle,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.LocalPort,
		arg.Subdomain,
		arg.RemotePort,
		arg.AutoConnect,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertBundleRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
