// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllCustomDomains = `-- name: CountAllCustomDomains :one
SELECT COUNT(*) FROM custom_domains
`

func (q *Queries) CountAllCustomDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCustomDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomDomainsByUserID = `-- name: CountCustomDomainsByUserID :one
SELECT COUNT(*) FROM custom_domains WHERE user_id = $1
`

func (q *Queries) CountCustomDomainsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomDomainsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (user_id, domain, target_subdomain, verified, created_at)
VALUES ($1, $2, $3, FALSE, NOW())
RETURNING id, created_at
`

type CreateCustomDomainParams struct {
	UserID          int64  `json:"user_id"`
	Domain          string `json:"domain"`
	TargetSubdomain string `json:"target_subdomain"`
}

type CreateCustomDomainRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CreateCustomDomainRow, error) {
	row := q.db.QueryRow(ctx, createCustomDomain, arg.UserID, arg.Domain, arg.TargetSubdomain)
	var i CreateCustomDomainRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
DELETE FROM custom_domains WHERE id = $1
`

func (q *Queries) DeleteCustomDomain(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomDomain, id)
	return err
}

const getCustomDomainByDomain = `-- name: GetCustomDomainByDomain :one
SELECT id, user_id, domain, target_subdomain, verified, verified_at, created_at
FROM custom_domains WHERE domain = $1
`

func (q *Queries) GetCustomDomainByDomain(ctx context.Context, domain string) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByDomain, domain)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.TargetSubdomain,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomDomainByID = `-- name: GetCustomDomainByID :one
SELECT id, user_id, domain, target_subdomain, verified, verified_at, created_at
FROM custom_domains WHERE id = $1
`

func (q *Queries) GetCustomDomainByID(ctx context.Context, id int64) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByID, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.TargetSubdomain,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCustomDomains = `-- name: ListAllCustomDomains :many
SELECT id, user_id, domain, target_subdomain, verified, verified_at, created_at
FROM custom_domains ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllCustomDomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllCustomDomains(ctx context.Context, arg ListAllCustomDomainsParams) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listAllCustomDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomDomain{}
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Domain,
			&i.TargetSubdomain,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomDomainsByUserID = `-- name: ListCustomDomainsByUserID :many
SELECT id, user_id, domain, target_subdomain, verified, verified_at, created_at
FROM custom_domains WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCustomDomainsByUserID(ctx context.Context, userID int64) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listCustomDomainsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomDomain{}
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Domain,
			&i.TargetSubdomain,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedCustomDomains = `-- name: ListVerifiedCustomDomains :many
SELECT id, user_id, domain, target_subdomain, verified, verified_at, created_at
FROM custom_domains WHERE verified = TRUE
`

func (q *Queries) ListVerifiedCustomDomains(ctx context.Context) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listVerifiedCustomDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomDomain{}
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Domain,
			&i.TargetSubdomain,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomDomainVerified = `-- name: SetCustomDomainVerified :exec
UPDATE custom_domains SET verified = $2, verified_at = $3 WHERE id = $1
`

type SetCustomDomainVerifiedParams struct {
	ID         int64              `json:"id"`
	Verified   bool               `json:"verified"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) SetCustomDomainVerified(ctx context.Context, arg SetCustomDomainVerifiedParams) error {
	_, err := q.db.Exec(ctx, setCustomDomainVerified, arg.ID, arg.Verified, arg.VerifiedAt)
	return err
}
