// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReservedDomainsByUserID = `-- name: CountReservedDomainsByUserID :one
SELECT COUNT(*) FROM reserved_domains WHERE user_id = $1
`

func (q *Queries) CountReservedDomainsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReservedDomainsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservedDomain = `-- name: CreateReservedDomain :one
INSERT INTO reserved_domains (user_id, subdomain, created_at)
VALUES ($1, $2, NOW())
RETURNING id, created_at
`

type CreateReservedDomainParams struct {
	UserID    int64  `json:"user_id"`
	Subdomain string `json:"subdomain"`
}

type CreateReservedDomainRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReservedDomain(ctx context.Context, arg CreateReservedDomainParams) (CreateReservedDomainRow, error) {
	row := q.db.QueryRow(ctx, createReservedDomain, arg.UserID, arg.Subdomain)
	var i CreateReservedDomainRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteReservedDomain = `-- name: DeleteReservedDomain :exec
DELETE FROM reserved_domains WHERE id = $1
`

func (q *Queries) DeleteReservedDomain(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReservedDomain, id)
	return err
}

const deleteReservedDomainsByUserID = `-- name: DeleteReservedDomainsByUserID :exec
DELETE FROM reserved_domains WHERE user_id = $1
`

func (q *Queries) DeleteReservedDomainsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteReservedDomainsByUserID, userID)
	return err
}

const getReservedDomainByID = `-- name: GetReservedDomainByID :one
SELECT id, user_id, subdomain, created_at FROM reserved_domains WHERE id = $1
`

func (q *Queries) GetReservedDomainByID(ctx context.Context, id int64) (ReservedDomain, error) {
	row := q.db.QueryRow(ctx, getReservedDomainByID, id)
	var i ReservedDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subdomain,
		&i.CreatedAt,
	)
	return i, err
}

const getReservedDomainBySubdomain = `-- name: GetReservedDomainBySubdomain :one
SELECT id, user_id, subdomain, created_at FROM reserved_domains WHERE subdomain = $1
`

func (q *Queries) GetReservedDomainBySubdomain(ctx context.Context, subdomain string) (ReservedDomain, error) {
	row := q.db.QueryRow(ctx, getReservedDomainBySubdomain, subdomain)
	var i ReservedDomain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subdomain,
		&i.CreatedAt,
	)
	return i, err
}

const isSubdomainAvailable = `-- name: IsSubdomainAvailable :one
SELECT COUNT(*) = 0 AS available FROM reserved_domains WHERE subdomain = $1
`

func (q *Queries) IsSubdomainAvailable(ctx context.Context, subdomain string) (bool, error) {
	row := q.db.QueryRow(ctx, isSubdomainAvailable, subdomain)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const isSubdomainOwnedByUser = `-- name: IsSubdomainOwnedByUser :one
SELECT COUNT(*) > 0 AS owned FROM reserved_domains WHERE subdomain = $1 AND user_id = $2
`

type IsSubdomainOwnedByUserParams struct {
	Subdomain string `json:"subdomain"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) IsSubdomainOwnedByUser(ctx context.Context, arg IsSubdomainOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSubdomainOwnedByUser, arg.Subdomain, arg.UserID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const listReservedDomainsByUserID = `-- name: ListReservedDomainsByUserID :many
SELECT id, user_id, subdomain, created_at FROM reserved_domains WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReservedDomainsByUserID(ctx context.Context, userID int64) ([]ReservedDomain, error) {
	rows, err := q.db.Query(ctx, listReservedDomainsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservedDomain{}
	for rows.Next() {
		var i ReservedDomain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subdomain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
