// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchanges.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExchangesByHostAndUser = `-- name: CountExchangesByHostAndUser :one
SELECT COUNT(*) FROM inspect_exchanges WHERE host = $1 AND user_id = $2
`

type CountExchangesByHostAndUserParams struct {
	Host   string `json:"host"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CountExchangesByHostAndUser(ctx context.Context, arg CountExchangesByHostAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExchangesByHostAndUser, arg.Host, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExchangesByTunnelID = `-- name: CountExchangesByTunnelID :one
SELECT COUNT(*) FROM inspect_exchanges WHERE tunnel_id = $1
`

func (q *Queries) CountExchangesByTunnelID(ctx context.Context, tunnelID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExchangesByTunnelID, tunnelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExchangesByTunnelID = `-- name: DeleteExchangesByTunnelID :execrows
DELETE FROM inspect_exchanges WHERE tunnel_id = $1
`

func (q *Queries) DeleteExchangesByTunnelID(ctx context.Context, tunnelID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExchangesByTunnelID, tunnelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExchangesOlderThan = `-- name: DeleteExchangesOlderThan :execrows
DELETE FROM inspect_exchanges WHERE created_at < $1
`

func (q *Queries) DeleteExchangesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExchangesOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExchangeByID = `-- name: GetExchangeByID :one
SELECT id, tunnel_id, trace_id, replay_ref, timestamp, duration_ns, method, path, host, request_headers, request_body, request_body_size, response_headers, response_body, response_body_size, status_code, remote_addr
FROM inspect_exchanges WHERE id = $1
`

type GetExchangeByIDRow struct {
	ID               string             `json:"id"`
	TunnelID         string             `json:"tunnel_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ReplayRef        pgtype.Text        `json:"replay_ref"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	DurationNs       int64              `json:"duration_ns"`
	Method           string             `json:"method"`
	Path             string             `json:"path"`
	Host             string             `json:"host"`
	RequestHeaders   []byte             `json:"request_headers"`
	RequestBody      []byte             `json:"request_body"`
	RequestBodySize  int32              `json:"request_body_size"`
	ResponseHeaders  []byte             `json:"response_headers"`
	ResponseBody     []byte             `json:"response_body"`
	ResponseBodySize int32              `json:"response_body_size"`
	StatusCode       int32              `json:"status_code"`
	RemoteAddr       pgtype.Text        `json:"remote_addr"`
}

func (q *Queries) GetExchangeByID(ctx context.Context, id string) (GetExchangeByIDRow, error) {
	row := q.db.QueryRow(ctx, getExchangeByID, id)
	var i GetExchangeByIDRow
	err := row.Scan(
		&i.ID,
		&i.TunnelID,
		&i.TraceID,
		&i.ReplayRef,
		&i.Timestamp,
		&i.DurationNs,
		&i.Method,
		&i.Path,
		&i.Host,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.RequestBodySize,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseBodySize,
		&i.StatusCode,
		&i.RemoteAddr,
	)
	return i, err
}

const listExchangesByHostAndUser = `-- name: ListExchangesByHostAndUser :many
SELECT id, tunnel_id, trace_id, replay_ref, timestamp, duration_ns, method, path, host, request_headers, request_body, request_body_size, response_headers, response_body, response_body_size, status_code, remote_addr
FROM inspect_exchanges WHERE host = $1 AND user_id = $2 ORDER BY timestamp DESC LIMIT $3 OFFSET $4
`

type ListExchangesByHostAndUserParams struct {
	Host   string `json:"host"`
	UserID int64  `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListExchangesByHostAndUserRow struct {
	ID               string             `json:"id"`
	TunnelID         string             `json:"tunnel_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ReplayRef        pgtype.Text        `json:"replay_ref"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	DurationNs       int64              `json:"duration_ns"`
	Method           string             `json:"method"`
	Path             string             `json:"path"`
	Host             string             `json:"host"`
	RequestHeaders   []byte             `json:"request_headers"`
	RequestBody      []byte             `json:"request_body"`
	RequestBodySize  int32              `json:"request_body_size"`
	ResponseHeaders  []byte             `json:"response_headers"`
	ResponseBody     []byte             `json:"response_body"`
	ResponseBodySize int32              `json:"response_body_size"`
	StatusCode       int32              `json:"status_code"`
	RemoteAddr       pgtype.Text        `json:"remote_addr"`
}

func (q *Queries) ListExchangesByHostAndUser(ctx context.Context, arg ListExchangesByHostAndUserParams) ([]ListExchangesByHostAndUserRow, error) {
	rows, err := q.db.Query(ctx, listExchangesByHostAndUser,
		arg.Host,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangesByHostAndUserRow{}
	for rows.Next() {
		var i ListExchangesByHostAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TunnelID,
			&i.TraceID,
			&i.ReplayRef,
			&i.Timestamp,
			&i.DurationNs,
			&i.Method,
			&i.Path,
			&i.Host,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.RequestBodySize,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseBodySize,
			&i.StatusCode,
			&i.RemoteAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangesByTunnelID = `-- name: ListExchangesByTunnelID :many
SELECT id, tunnel_id, trace_id, replay_ref, timestamp, duration_ns, method, path, host, request_headers, request_body, request_body_size, response_headers, response_body, response_body_size, status_code, remote_addr
FROM inspect_exchanges WHERE tunnel_id = $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type ListExchangesByTunnelIDParams struct {
	TunnelID string `json:"tunnel_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListExchangesByTunnelIDRow struct {
	ID               string             `json:"id"`
	TunnelID         string             `json:"tunnel_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ReplayRef        pgtype.Text        `json:"replay_ref"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	DurationNs       int64              `json:"duration_ns"`
	Method           string             `json:"method"`
	Path             string             `json:"path"`
	Host             string             `json:"host"`
	RequestHeaders   []byte             `json:"request_headers"`
	RequestBody      []byte             `json:"request_body"`
	RequestBodySize  int32              `json:"request_body_size"`
	ResponseHeaders  []byte             `json:"response_headers"`
	ResponseBody     []byte             `json:"response_body"`
	ResponseBodySize int32              `json:"response_body_size"`
	StatusCode       int32              `json:"status_code"`
	RemoteAddr       pgtype.Text        `json:"remote_addr"`
}

func (q *Queries) ListExchangesByTunnelID(ctx context.Context, arg ListExchangesByTunnelIDParams) ([]ListExchangesByTunnelIDRow, error) {
	rows, err := q.db.Query(ctx, listExchangesByTunnelID, arg.TunnelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangesByTunnelIDRow{}
	for rows.Next() {
		var i ListExchangesByTunnelIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TunnelID,
			&i.TraceID,
			&i.ReplayRef,
			&i.Timestamp,
			&i.DurationNs,
			&i.Method,
			&i.Path,
			&i.Host,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.RequestBodySize,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseBodySize,
			&i.StatusCode,
			&i.RemoteAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveExchange = `-- name: SaveExchange :exec
INSERT INTO inspect_exchanges (id, tunnel_id, user_id, trace_id, replay_ref, timestamp, duration_ns, method, path, host, request_headers, request_body, request_body_size, response_headers, response_body, response_body_size, status_code, remote_addr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type SaveExchangeParams struct {
	ID               string             `json:"id"`
	TunnelID         string             `json:"tunnel_id"`
	UserID           int64              `json:"user_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ReplayRef        pgtype.Text        `json:"replay_ref"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	DurationNs       int64              `json:"duration_ns"`
	Method           string             `json:"method"`
	Path             string             `json:"path"`
	Host             string             `json:"host"`
	RequestHeaders   []byte             `json:"request_headers"`
	RequestBody      []byte             `json:"request_body"`
	RequestBodySize  int32              `json:"request_body_size"`
	ResponseHeaders  []byte             `json:"response_headers"`
	ResponseBody     []byte             `json:"response_body"`
	ResponseBodySize int32              `json:"response_body_size"`
	StatusCode       int32              `json:"status_code"`
	RemoteAddr       pgtype.Text        `json:"remote_addr"`
}

func (q *Queries) SaveExchange(ctx context.Context, arg SaveExchangeParams) error {
	_, err := q.db.Exec(ctx, saveExchange,
		arg.ID,
		arg.TunnelID,
		arg.UserID,
		arg.TraceID,
		arg.ReplayRef,
		arg.Timestamp,
		arg.DurationNs,
		arg.Method,
		arg.Path,
		arg.Host,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.RequestBodySize,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseBodySize,
		arg.StatusCode,
		arg.RemoteAddr,
	)
	return err
}
