// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM user_history WHERE user_id = $1
`

func (q *Queries) ClearHistory(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearHistory, userID)
	return err
}

const countHistoryByUserID = `-- name: CountHistoryByUserID :one
SELECT COUNT(*) FROM user_history WHERE user_id = $1
`

func (q *Queries) CountHistoryByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countHistoryByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHistoryEntry = `-- name: CreateHistoryEntry :one
INSERT INTO user_history (user_id, bundle_name, tunnel_type, local_port, remote_addr, url, connected_at, disconnected_at, bytes_sent, bytes_received)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateHistoryEntryParams struct {
	UserID         int64              `json:"user_id"`
	BundleName     pgtype.Text        `json:"bundle_name"`
	TunnelType     string             `json:"tunnel_type"`
	LocalPort      int32              `json:"local_port"`
	RemoteAddr     pgtype.Text        `json:"remote_addr"`
	Url            pgtype.Text        `json:"url"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	BytesSent      int64              `json:"bytes_sent"`
	BytesReceived  int64              `json:"bytes_received"`
}

func (q *Queries) CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createHistoryEntry,
		arg.UserID,
		arg.BundleName,
		arg.TunnelType,
		arg.LocalPort,
		arg.RemoteAddr,
		arg.Url,
		arg.ConnectedAt,
		arg.DisconnectedAt,
		arg.BytesSent,
		arg.BytesReceived,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteHistoryOlderThan = `-- name: DeleteHistoryOlderThan :execrows
DELETE FROM user_history WHERE user_id = $1 AND connected_at < $2
`

type DeleteHistoryOlderThanParams struct {
	UserID      int64              `json:"user_id"`
	ConnectedAt pgtype.Timestamptz `json:"connected_at"`
}

func (q *Queries) DeleteHistoryOlderThan(ctx context.Context, arg DeleteHistoryOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHistoryOlderThan, arg.UserID, arg.ConnectedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHistoryEntryByID = `-- name: GetHistoryEntryByID :one
SELECT id, user_id, bundle_name, tunnel_type, local_port, remote_addr, url, connected_at, disconnected_at, bytes_sent, bytes_received
FROM user_history WHERE id = $1 AND user_id = $2
`

type GetHistoryEntryByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetHistoryEntryByID(ctx context.Context, arg GetHistoryEntryByIDParams) (UserHistory, error) {
	row := q.db.QueryRow(ctx, getHistoryEntryByID, arg.ID, arg.UserID)
	var i UserHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BundleName,
		&i.TunnelType,
		&i.LocalPort,
		&i.RemoteAddr,
		&i.Url,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.BytesSent,
		&i.BytesReceived,
	)
	return i, err
}

const getHistoryStats = `-- name: GetHistoryStats :one
SELECT
    COUNT(*) AS total_connections,
    COALESCE(SUM(bytes_sent), 0) AS total_bytes_sent,
    COALESCE(SUM(bytes_received), 0) AS total_bytes_received
FROM user_history WHERE user_id = $1
`

type GetHistoryStatsRow struct {
	TotalConnections   int64       `json:"total_connections"`
	TotalBytesSent     interface{} `json:"total_bytes_sent"`
	TotalBytesReceived interface{} `json:"total_bytes_received"`
}

func (q *Queries) GetHistoryStats(ctx context.Context, userID int64) (GetHistoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getHistoryStats, userID)
	var i GetHistoryStatsRow
	err := row.Scan(&i.TotalConnections, &i.TotalBytesSent, &i.TotalBytesReceived)
	return i, err
}

const listHistoryByUserID = `-- name: ListHistoryByUserID :many
SELECT id, user_id, bundle_name, tunnel_type, local_port, remote_addr, url, connected_at, disconnected_at, bytes_sent, bytes_received
FROM user_history WHERE user_id = $1 ORDER BY connected_at DESC LIMIT $2 OFFSET $3
`

type ListHistoryByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListHistoryByUserID(ctx context.Context, arg ListHistoryByUserIDParams) ([]UserHistory, error) {
	rows, err := q.db.Query(ctx, listHistoryByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserHistory{}
	for rows.Next() {
		var i UserHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BundleName,
			&i.TunnelType,
			&i.LocalPort,
			&i.RemoteAddr,
			&i.Url,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.BytesSent,
			&i.BytesReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHistoryEntry = `-- name: UpdateHistoryEntry :exec
UPDATE user_history SET disconnected_at = $3, bytes_sent = $4, bytes_received = $5
WHERE id = $1 AND user_id = $2
`

type UpdateHistoryEntryParams struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	BytesSent      int64              `json:"bytes_sent"`
	BytesReceived  int64              `json:"bytes_received"`
}

func (q *Queries) UpdateHistoryEntry(ctx context.Context, arg UpdateHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, updateHistoryEntry,
		arg.ID,
		arg.UserID,
		arg.DisconnectedAt,
		arg.BytesSent,
		arg.BytesReceived,
	)
	return err
}
