// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	Name              string             `json:"name"`
	AllowedSubdomains json.RawMessage    `json:"allowed_subdomains"`
	MaxTunnels        int32              `json:"max_tunnels"`
	AllowedIps        json.RawMessage    `json:"allowed_ips"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Action    string             `json:"action"`
	Details   []byte             `json:"details"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CustomDomain struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Domain          string             `json:"domain"`
	TargetSubdomain string             `json:"target_subdomain"`
	Verified        bool               `json:"verified"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type EdgeNode struct {
	ID              int64              `json:"id"`
	NodeID          string             `json:"node_id"`
	Name            string             `json:"name"`
	Region          string             `json:"region"`
	PublicAddr      string             `json:"public_addr"`
	HttpAddr        string             `json:"http_addr"`
	Status          string             `json:"status"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy      pgtype.Int8        `json:"approved_by"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Version         string             `json:"version"`
	Metadata        json.RawMessage    `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type InspectExchange struct {
	ID               string             `json:"id"`
	TunnelID         string             `json:"tunnel_id"`
	UserID           int64              `json:"user_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ReplayRef        pgtype.Text        `json:"replay_ref"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	DurationNs       int64              `json:"duration_ns"`
	Method           string             `json:"method"`
	Path             string             `json:"path"`
	Host             string             `json:"host"`
	RequestHeaders   []byte             `json:"request_headers"`
	RequestBody      []byte             `json:"request_body"`
	RequestBodySize  int32              `json:"request_body_size"`
	ResponseHeaders  []byte             `json:"response_headers"`
	ResponseBody     []byte             `json:"response_body"`
	ResponseBodySize int32              `json:"response_body_size"`
	StatusCode       int32              `json:"status_code"`
	RemoteAddr       pgtype.Text        `json:"remote_addr"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type InviteCode struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	UsedByUserID    pgtype.Int8        `json:"used_by_user_id"`
	UsedAt          pgtype.Timestamptz `json:"used_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	InvoiceID      int64              `json:"invoice_id"`
	Amount         float64            `json:"amount"`
	Status         string             `json:"status"`
	IsRecurring    bool               `json:"is_recurring"`
	YookassaData   pgtype.Text        `json:"yookassa_data"`
	Provider       string             `json:"provider"`
	ProviderData   pgtype.Text        `json:"provider_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID                 int64   `json:"id"`
	Slug               string  `json:"slug"`
	Name               string  `json:"name"`
	Price              float64 `json:"price"`
	MaxTunnels         int32   `json:"max_tunnels"`
	MaxDomains         int32   `json:"max_domains"`
	MaxCustomDomains   int32   `json:"max_custom_domains"`
	MaxTokens          int32   `json:"max_tokens"`
	MaxTunnelsPerToken int32   `json:"max_tunnels_per_token"`
	InspectorEnabled   bool    `json:"inspector_enabled"`
	IsPublic           bool    `json:"is_public"`
	IsRecommended      bool    `json:"is_recommended"`
	BandwidthMbps      int32   `json:"bandwidth_mbps"`
	RateLimitTcp       int32   `json:"rate_limit_tcp"`
	RateLimitUdp       int32   `json:"rate_limit_udp"`
	RateLimitHttp      int32   `json:"rate_limit_http"`
	CreemProductID     string  `json:"creem_product_id"`
	MaxDataSessions    int32   `json:"max_data_sessions"`
	UdpEnabled         bool    `json:"udp_enabled"`
}

type ReservedDomain struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Subdomain string             `json:"subdomain"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                      int64              `json:"id"`
	UserID                  int64              `json:"user_id"`
	PlanID                  int64              `json:"plan_id"`
	NextPlanID              pgtype.Int8        `json:"next_plan_id"`
	Status                  string             `json:"status"`
	Recurring               bool               `json:"recurring"`
	CurrentPeriodStart      pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd        pgtype.Timestamptz `json:"current_period_end"`
	YookassaPaymentMethodID pgtype.Text        `json:"yookassa_payment_method_id"`
	CreemCustomerID         pgtype.Text        `json:"creem_customer_id"`
	CreemSubscriptionID     pgtype.Text        `json:"creem_subscription_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type TlsCertificate struct {
	ID        int64              `json:"id"`
	Domain    string             `json:"domain"`
	CertPem   []byte             `json:"cert_pem"`
	KeyPem    []byte             `json:"key_pem"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TotpSecret struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	SecretEncrypted string             `json:"secret_encrypted"`
	IsEnabled       bool               `json:"is_enabled"`
	BackupCodes     []byte             `json:"backup_codes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int64              `json:"id"`
	Phone         pgtype.Text        `json:"phone"`
	PasswordHash  string             `json:"password_hash"`
	DisplayName   pgtype.Text        `json:"display_name"`
	IsAdmin       bool               `json:"is_admin"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	GithubID      pgtype.Int8        `json:"github_id"`
	Email         pgtype.Text        `json:"email"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	GoogleID      pgtype.Text        `json:"google_id"`
	PlanID        pgtype.Int8        `json:"plan_id"`
	FirstTunnelAt pgtype.Timestamptz `json:"first_tunnel_at"`
}

type UserBundle struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	LocalPort   int32              `json:"local_port"`
	Subdomain   pgtype.Text        `json:"subdomain"`
	RemotePort  pgtype.Int4        `json:"remote_port"`
	AutoConnect bool               `json:"auto_connect"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserHistory struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	BundleName     pgtype.Text        `json:"bundle_name"`
	TunnelType     string             `json:"tunnel_type"`
	LocalPort      int32              `json:"local_port"`
	RemoteAddr     pgtype.Text        `json:"remote_addr"`
	Url            pgtype.Text        `json:"url"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	BytesSent      int64              `json:"bytes_sent"`
	BytesReceived  int64              `json:"bytes_received"`
}

type UserSetting struct {
	UserID    int64              `json:"user_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
