// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllPayments = `-- name: CountAllPayments :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountAllPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByUserID = `-- name: CountPaymentsByUserID :one
SELECT COUNT(*) FROM payments WHERE user_id = $1
`

func (q *Queries) CountPaymentsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, created_at
`

type CreatePaymentParams struct {
	UserID         int64       `json:"user_id"`
	SubscriptionID pgtype.Int8 `json:"subscription_id"`
	InvoiceID      int64       `json:"invoice_id"`
	Amount         float64     `json:"amount"`
	Status         string      `json:"status"`
	IsRecurring    bool        `json:"is_recurring"`
	YookassaData   pgtype.Text `json:"yookassa_data"`
	Provider       string      `json:"provider"`
	ProviderData   pgtype.Text `json:"provider_data"`
}

type CreatePaymentRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.SubscriptionID,
		arg.InvoiceID,
		arg.Amount,
		arg.Status,
		arg.IsRecurring,
		arg.YookassaData,
		arg.Provider,
		arg.ProviderData,
	)
	var i CreatePaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const expireStalePendingSubscriptions = `-- name: ExpireStalePendingSubscriptions :exec
UPDATE subscriptions SET status = 'expired', updated_at = NOW()
WHERE status = 'pending' AND id IN (
    SELECT subscription_id FROM payments p WHERE p.status = 'pending' AND p.created_at < $1
)
`

func (q *Queries) ExpireStalePendingSubscriptions(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireStalePendingSubscriptions, createdAt)
	return err
}

const failStalePendingPayments = `-- name: FailStalePendingPayments :execrows
UPDATE payments SET status = 'failed' WHERE status = 'pending' AND created_at < $1
`

func (q *Queries) FailStalePendingPayments(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, failStalePendingPayments, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNextInvoiceID = `-- name: GetNextInvoiceID :one
SELECT COALESCE(MAX(invoice_id), 100000) + 1 AS next_id FROM payments
`

func (q *Queries) GetNextInvoiceID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextInvoiceID)
	var next_id int32
	err := row.Scan(&next_id)
	return next_id, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at
FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.InvoiceID,
		&i.Amount,
		&i.Status,
		&i.IsRecurring,
		&i.YookassaData,
		&i.Provider,
		&i.ProviderData,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByInvoiceID = `-- name: GetPaymentByInvoiceID :one
SELECT id, user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at
FROM payments WHERE invoice_id = $1
`

func (q *Queries) GetPaymentByInvoiceID(ctx context.Context, invoiceID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByInvoiceID, invoiceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.InvoiceID,
		&i.Amount,
		&i.Status,
		&i.IsRecurring,
		&i.YookassaData,
		&i.Provider,
		&i.ProviderData,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingPaymentsBySubscriptionID = `-- name: GetPendingPaymentsBySubscriptionID :many
SELECT id, user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at
FROM payments WHERE subscription_id = $1 AND status = 'pending' ORDER BY created_at DESC
`

func (q *Queries) GetPendingPaymentsBySubscriptionID(ctx context.Context, subscriptionID pgtype.Int8) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPendingPaymentsBySubscriptionID, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.InvoiceID,
			&i.Amount,
			&i.Status,
			&i.IsRecurring,
			&i.YookassaData,
			&i.Provider,
			&i.ProviderData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT id, user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at
FROM payments ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listAllPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.InvoiceID,
			&i.Amount,
			&i.Status,
			&i.IsRecurring,
			&i.YookassaData,
			&i.Provider,
			&i.ProviderData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT id, user_id, subscription_id, invoice_id, amount, status, is_recurring, yookassa_data, provider, provider_data, created_at
FROM payments WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByUserID(ctx context.Context, arg ListPaymentsByUserIDParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.InvoiceID,
			&i.Amount,
			&i.Status,
			&i.IsRecurring,
			&i.YookassaData,
			&i.Provider,
			&i.ProviderData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments SET subscription_id = $2, status = $3, yookassa_data = $4, provider = $5, provider_data = $6
WHERE id = $1
`

type UpdatePaymentParams struct {
	ID             int64       `json:"id"`
	SubscriptionID pgtype.Int8 `json:"subscription_id"`
	Status         string      `json:"status"`
	YookassaData   pgtype.Text `json:"yookassa_data"`
	Provider       string      `json:"provider"`
	ProviderData   pgtype.Text `json:"provider_data"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.Exec(ctx, updatePayment,
		arg.ID,
		arg.SubscriptionID,
		arg.Status,
		arg.YookassaData,
		arg.Provider,
		arg.ProviderData,
	)
	return err
}
