// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllPlans = `-- name: CountAllPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountAllPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlanUsers = `-- name: CountPlanUsers :one
SELECT COUNT(*) FROM users WHERE plan_id = $1
`

func (q *Queries) CountPlanUsers(ctx context.Context, planID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countPlanUsers, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (slug, name, price, max_tunnels, max_domains, max_custom_domains,
                   max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
                   is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
                   rate_limit_http, creem_product_id, max_data_sessions, udp_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id
`

type CreatePlanParams struct {
	Slug               string  `json:"slug"`
	Name               string  `json:"name"`
	Price              float64 `json:"price"`
	MaxTunnels         int32   `json:"max_tunnels"`
	MaxDomains         int32   `json:"max_domains"`
	MaxCustomDomains   int32   `json:"max_custom_domains"`
	MaxTokens          int32   `json:"max_tokens"`
	MaxTunnelsPerToken int32   `json:"max_tunnels_per_token"`
	InspectorEnabled   bool    `json:"inspector_enabled"`
	IsPublic           bool    `json:"is_public"`
	IsRecommended      bool    `json:"is_recommended"`
	BandwidthMbps      int32   `json:"bandwidth_mbps"`
	RateLimitTcp       int32   `json:"rate_limit_tcp"`
	RateLimitUdp       int32   `json:"rate_limit_udp"`
	RateLimitHttp      int32   `json:"rate_limit_http"`
	CreemProductID     string  `json:"creem_product_id"`
	MaxDataSessions    int32   `json:"max_data_sessions"`
	UdpEnabled         bool    `json:"udp_enabled"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Slug,
		arg.Name,
		arg.Price,
		arg.MaxTunnels,
		arg.MaxDomains,
		arg.MaxCustomDomains,
		arg.MaxTokens,
		arg.MaxTunnelsPerToken,
		arg.InspectorEnabled,
		arg.IsPublic,
		arg.IsRecommended,
		arg.BandwidthMbps,
		arg.RateLimitTcp,
		arg.RateLimitUdp,
		arg.RateLimitHttp,
		arg.CreemProductID,
		arg.MaxDataSessions,
		arg.UdpEnabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getDefaultPlan = `-- name: GetDefaultPlan :one
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans WHERE slug = 'free' LIMIT 1
`

func (q *Queries) GetDefaultPlan(ctx context.Context) (Plan, error) {
	row := q.db.QueryRow(ctx, getDefaultPlan)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.MaxTunnels,
		&i.MaxDomains,
		&i.MaxCustomDomains,
		&i.MaxTokens,
		&i.MaxTunnelsPerToken,
		&i.InspectorEnabled,
		&i.IsPublic,
		&i.IsRecommended,
		&i.BandwidthMbps,
		&i.RateLimitTcp,
		&i.RateLimitUdp,
		&i.RateLimitHttp,
		&i.CreemProductID,
		&i.MaxDataSessions,
		&i.UdpEnabled,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.MaxTunnels,
		&i.MaxDomains,
		&i.MaxCustomDomains,
		&i.MaxTokens,
		&i.MaxTunnelsPerToken,
		&i.InspectorEnabled,
		&i.IsPublic,
		&i.IsRecommended,
		&i.BandwidthMbps,
		&i.RateLimitTcp,
		&i.RateLimitUdp,
		&i.RateLimitHttp,
		&i.CreemProductID,
		&i.MaxDataSessions,
		&i.UdpEnabled,
	)
	return i, err
}

const getPlanBySlug = `-- name: GetPlanBySlug :one
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans WHERE slug = $1
`

func (q *Queries) GetPlanBySlug(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanBySlug, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.MaxTunnels,
		&i.MaxDomains,
		&i.MaxCustomDomains,
		&i.MaxTokens,
		&i.MaxTunnelsPerToken,
		&i.InspectorEnabled,
		&i.IsPublic,
		&i.IsRecommended,
		&i.BandwidthMbps,
		&i.RateLimitTcp,
		&i.RateLimitUdp,
		&i.RateLimitHttp,
		&i.CreemProductID,
		&i.MaxDataSessions,
		&i.UdpEnabled,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans ORDER BY price ASC LIMIT $1 OFFSET $2
`

type ListAllPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllPlans(ctx context.Context, arg ListAllPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listAllPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Price,
			&i.MaxTunnels,
			&i.MaxDomains,
			&i.MaxCustomDomains,
			&i.MaxTokens,
			&i.MaxTunnelsPerToken,
			&i.InspectorEnabled,
			&i.IsPublic,
			&i.IsRecommended,
			&i.BandwidthMbps,
			&i.RateLimitTcp,
			&i.RateLimitUdp,
			&i.RateLimitHttp,
			&i.CreemProductID,
			&i.MaxDataSessions,
			&i.UdpEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans ORDER BY price ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Price,
			&i.MaxTunnels,
			&i.MaxDomains,
			&i.MaxCustomDomains,
			&i.MaxTokens,
			&i.MaxTunnelsPerToken,
			&i.InspectorEnabled,
			&i.IsPublic,
			&i.IsRecommended,
			&i.BandwidthMbps,
			&i.RateLimitTcp,
			&i.RateLimitUdp,
			&i.RateLimitHttp,
			&i.CreemProductID,
			&i.MaxDataSessions,
			&i.UdpEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPlans = `-- name: ListPublicPlans :many
SELECT id, slug, name, price, max_tunnels, max_domains, max_custom_domains,
       max_tokens, max_tunnels_per_token, inspector_enabled, is_public,
       is_recommended, bandwidth_mbps, rate_limit_tcp, rate_limit_udp,
       rate_limit_http, creem_product_id, max_data_sessions, udp_enabled
FROM plans WHERE is_public = TRUE ORDER BY price ASC
`

func (q *Queries) ListPublicPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPublicPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Price,
			&i.MaxTunnels,
			&i.MaxDomains,
			&i.MaxCustomDomains,
			&i.MaxTokens,
			&i.MaxTunnelsPerToken,
			&i.InspectorEnabled,
			&i.IsPublic,
			&i.IsRecommended,
			&i.BandwidthMbps,
			&i.RateLimitTcp,
			&i.RateLimitUdp,
			&i.RateLimitHttp,
			&i.CreemProductID,
			&i.MaxDataSessions,
			&i.UdpEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET
    name = $2, price = $3, max_tunnels = $4, max_domains = $5,
    max_custom_domains = $6, max_tokens = $7, max_tunnels_per_token = $8,
    inspector_enabled = $9, is_public = $10, is_recommended = $11,
    bandwidth_mbps = $12, rate_limit_tcp = $13, rate_limit_udp = $14,
    rate_limit_http = $15, creem_product_id = $16, max_data_sessions = $17,
    udp_enabled = $18
WHERE id = $1
`

type UpdatePlanParams struct {
	ID                 int64   `json:"id"`
	Name               string  `json:"name"`
	Price              float64 `json:"price"`
	MaxTunnels         int32   `json:"max_tunnels"`
	MaxDomains         int32   `json:"max_domains"`
	MaxCustomDomains   int32   `json:"max_custom_domains"`
	MaxTokens          int32   `json:"max_tokens"`
	MaxTunnelsPerToken int32   `json:"max_tunnels_per_token"`
	InspectorEnabled   bool    `json:"inspector_enabled"`
	IsPublic           bool    `json:"is_public"`
	IsRecommended      bool    `json:"is_recommended"`
	BandwidthMbps      int32   `json:"bandwidth_mbps"`
	RateLimitTcp       int32   `json:"rate_limit_tcp"`
	RateLimitUdp       int32   `json:"rate_limit_udp"`
	RateLimitHttp      int32   `json:"rate_limit_http"`
	CreemProductID     string  `json:"creem_product_id"`
	MaxDataSessions    int32   `json:"max_data_sessions"`
	UdpEnabled         bool    `json:"udp_enabled"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.MaxTunnels,
		arg.MaxDomains,
		arg.MaxCustomDomains,
		arg.MaxTokens,
		arg.MaxTunnelsPerToken,
		arg.InspectorEnabled,
		arg.IsPublic,
		arg.IsRecommended,
		arg.BandwidthMbps,
		arg.RateLimitTcp,
		arg.RateLimitUdp,
		arg.RateLimitHttp,
		arg.CreemProductID,
		arg.MaxDataSessions,
		arg.UdpEnabled,
	)
	return err
}
