// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearHistory(ctx context.Context, userID int64) error
	ClearSettings(ctx context.Context, userID int64) error
	CountAPITokensByUserID(ctx context.Context, userID int64) (int64, error)
	CountAllCustomDomains(ctx context.Context) (int64, error)
	CountAllPayments(ctx context.Context) (int64, error)
	CountAllPlans(ctx context.Context) (int64, error)
	CountAllSubscriptions(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuditLogsByAction(ctx context.Context, action string) (int64, error)
	CountAuditLogsByUserID(ctx context.Context, userID pgtype.Int8) (int64, error)
	CountBundlesByUserID(ctx context.Context, userID int64) (int64, error)
	CountCustomDomainsByUserID(ctx context.Context, userID int64) (int64, error)
	CountExchangesByHostAndUser(ctx context.Context, arg CountExchangesByHostAndUserParams) (int64, error)
	CountExchangesByTunnelID(ctx context.Context, tunnelID string) (int64, error)
	CountHistoryByUserID(ctx context.Context, userID int64) (int64, error)
	CountPaymentsByUserID(ctx context.Context, userID int64) (int64, error)
	CountPlanUsers(ctx context.Context, planID pgtype.Int8) (int64, error)
	CountReservedDomainsByUserID(ctx context.Context, userID int64) (int64, error)
	CountSettingsByUserID(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBundle(ctx context.Context, arg CreateBundleParams) (CreateBundleRow, error)
	CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CreateCustomDomainRow, error)
	CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (int64, error)
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (CreateOAuthUserRow, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (int64, error)
	CreateReservedDomain(ctx context.Context, arg CreateReservedDomainParams) (CreateReservedDomainRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error)
	CreateTOTPSecret(ctx context.Context, arg CreateTOTPSecretParams) (CreateTOTPSecretRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAPIToken(ctx context.Context, id int64) error
	DeleteAPITokensByUserID(ctx context.Context, userID int64) error
	DeleteAllBundles(ctx context.Context, userID int64) error
	DeleteAuditLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteBundle(ctx context.Context, arg DeleteBundleParams) error
	DeleteBundleByName(ctx context.Context, arg DeleteBundleByNameParams) error
	DeleteCustomDomain(ctx context.Context, id int64) error
	DeleteExchangesByTunnelID(ctx context.Context, tunnelID string) (int64, error)
	DeleteExchangesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteHistoryOlderThan(ctx context.Context, arg DeleteHistoryOlderThanParams) (int64, error)
	DeletePlan(ctx context.Context, id int64) error
	DeleteReservedDomain(ctx context.Context, id int64) error
	DeleteReservedDomainsByUserID(ctx context.Context, userID int64) error
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionByTokenHash(ctx context.Context, refreshTokenHash string) error
	DeleteSessionsByUserID(ctx context.Context, userID int64) error
	DeleteSetting(ctx context.Context, arg DeleteSettingParams) error
	DeleteSubscription(ctx context.Context, id int64) error
	DeleteTLSCertByDomain(ctx context.Context, domain string) error
	DeleteTOTP(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DisableTOTP(ctx context.Context, userID int64) error
	EnableTOTP(ctx context.Context, userID int64) error
	ExpireStalePendingSubscriptions(ctx context.Context, createdAt pgtype.Timestamptz) error
	FailStalePendingPayments(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, id int64) (ApiToken, error)
	GetActiveSubscriptionByUserID(ctx context.Context, userID int64) (Subscription, error)
	GetAllSettings(ctx context.Context, userID int64) ([]GetAllSettingsRow, error)
	GetAllSettingsWithTimestamps(ctx context.Context, userID int64) ([]UserSetting, error)
	GetBundleByID(ctx context.Context, arg GetBundleByIDParams) (UserBundle, error)
	GetBundleByName(ctx context.Context, arg GetBundleByNameParams) (UserBundle, error)
	GetCustomDomainByDomain(ctx context.Context, domain string) (CustomDomain, error)
	GetCustomDomainByID(ctx context.Context, id int64) (CustomDomain, error)
	GetDefaultPlan(ctx context.Context) (Plan, error)
	GetExchangeByID(ctx context.Context, id string) (GetExchangeByIDRow, error)
	GetExpiredSubscriptions(ctx context.Context) ([]Subscription, error)
	GetExpiringSubscriptions(ctx context.Context, currentPeriodEnd pgtype.Timestamptz) ([]Subscription, error)
	GetHistoryEntryByID(ctx context.Context, arg GetHistoryEntryByIDParams) (UserHistory, error)
	GetHistoryStats(ctx context.Context, userID int64) (GetHistoryStatsRow, error)
	GetLatestAuditLogByUserAndAction(ctx context.Context, arg GetLatestAuditLogByUserAndActionParams) (AuditLog, error)
	GetNextInvoiceID(ctx context.Context) (int32, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetPaymentByInvoiceID(ctx context.Context, invoiceID int64) (Payment, error)
	GetPendingPaymentsBySubscriptionID(ctx context.Context, subscriptionID pgtype.Int8) ([]Payment, error)
	GetPendingSubscriptionByUserID(ctx context.Context, userID int64) (Subscription, error)
	GetPlanByID(ctx context.Context, id int64) (Plan, error)
	GetPlanBySlug(ctx context.Context, slug string) (Plan, error)
	GetReservedDomainByID(ctx context.Context, id int64) (ReservedDomain, error)
	GetReservedDomainBySubdomain(ctx context.Context, subdomain string) (ReservedDomain, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID int64) ([]Session, error)
	GetSetting(ctx context.Context, arg GetSettingParams) (string, error)
	GetSubscriptionByCreemID(ctx context.Context, creemSubscriptionID pgtype.Text) (Subscription, error)
	GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error)
	GetSubscriptionsForRenewalReminder(ctx context.Context, arg GetSubscriptionsForRenewalReminderParams) ([]Subscription, error)
	GetSubscriptionsWithPendingPlanChange(ctx context.Context) ([]Subscription, error)
	GetTLSCertByDomain(ctx context.Context, domain string) (TlsCertificate, error)
	GetTOTPByUserID(ctx context.Context, userID int64) (TotpSecret, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByGitHubID(ctx context.Context, githubID pgtype.Int8) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error)
	GetUserStats(ctx context.Context, search pgtype.Text) (GetUserStatsRow, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]User, error)
	IsSubdomainAvailable(ctx context.Context, subdomain string) (bool, error)
	IsSubdomainOwnedByUser(ctx context.Context, arg IsSubdomainOwnedByUserParams) (bool, error)
	IsTOTPEnabled(ctx context.Context, userID int64) (bool, error)
	LinkGitHub(ctx context.Context, arg LinkGitHubParams) error
	LinkGoogle(ctx context.Context, arg LinkGoogleParams) error
	ListAPITokensByUserID(ctx context.Context, userID int64) ([]ApiToken, error)
	ListAllCustomDomains(ctx context.Context, arg ListAllCustomDomainsParams) ([]CustomDomain, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error)
	ListAllPlans(ctx context.Context, arg ListAllPlansParams) ([]Plan, error)
	ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]Subscription, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByUserID(ctx context.Context, arg ListAuditLogsByUserIDParams) ([]AuditLog, error)
	ListBundlesByUserID(ctx context.Context, userID int64) ([]UserBundle, error)
	ListCustomDomainsByUserID(ctx context.Context, userID int64) ([]CustomDomain, error)
	ListExchangesByHostAndUser(ctx context.Context, arg ListExchangesByHostAndUserParams) ([]ListExchangesByHostAndUserRow, error)
	ListExchangesByTunnelID(ctx context.Context, arg ListExchangesByTunnelIDParams) ([]ListExchangesByTunnelIDRow, error)
	ListExpiringTLSCerts(ctx context.Context, expiresAt pgtype.Timestamptz) ([]TlsCertificate, error)
	ListHistoryByUserID(ctx context.Context, arg ListHistoryByUserIDParams) ([]UserHistory, error)
	ListPaymentsByUserID(ctx context.Context, arg ListPaymentsByUserIDParams) ([]Payment, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListPublicPlans(ctx context.Context) ([]Plan, error)
	ListReservedDomainsByUserID(ctx context.Context, userID int64) ([]ReservedDomain, error)
	ListSubscriptionsByUserID(ctx context.Context, userID int64) ([]Subscription, error)
	ListUsersFiltered(ctx context.Context, arg ListUsersFilteredParams) ([]User, error)
	ListVerifiedCustomDomains(ctx context.Context) ([]CustomDomain, error)
	SaveExchange(ctx context.Context, arg SaveExchangeParams) error
	SetCustomDomainVerificationToken(ctx context.Context, arg SetCustomDomainVerificationTokenParams) error
	SetCustomDomainVerified(ctx context.Context, arg SetCustomDomainVerifiedParams) error
	SetFirstTunnelAt(ctx context.Context, arg SetFirstTunnelAtParams) (int64, error)
	UpdateAPITokenLastUsed(ctx context.Context, id int64) error
	UpdateBundle(ctx context.Context, arg UpdateBundleParams) error
	UpdateHistoryEntry(ctx context.Context, arg UpdateHistoryEntryParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) error
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
	UpdateTOTPBackupCodes(ctx context.Context, arg UpdateTOTPBackupCodesParams) error
	UpdateTOTPSecret(ctx context.Context, arg UpdateTOTPSecretParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error
	UpsertBundle(ctx context.Context, arg UpsertBundleParams) (UpsertBundleRow, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertSettingIfNewer(ctx context.Context, arg UpsertSettingIfNewerParams) error
	UpsertTLSCertificate(ctx context.Context, arg UpsertTLSCertificateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
