// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSettings = `-- name: ClearSettings :exec
DELETE FROM user_settings WHERE user_id = $1
`

func (q *Queries) ClearSettings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearSettings, userID)
	return err
}

const countSettingsByUserID = `-- name: CountSettingsByUserID :one
SELECT COUNT(*) FROM user_settings WHERE user_id = $1
`

func (q *Queries) CountSettingsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSettingsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM user_settings WHERE user_id = $1 AND key = $2
`

type DeleteSettingParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.Exec(ctx, deleteSetting, arg.UserID, arg.Key)
	return err
}

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value FROM user_settings WHERE user_id = $1
`

type GetAllSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetAllSettings(ctx context.Context, userID int64) ([]GetAllSettingsRow, error) {
	rows, err := q.db.Query(ctx, getAllSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSettingsRow{}
	for rows.Next() {
		var i GetAllSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSettingsWithTimestamps = `-- name: GetAllSettingsWithTimestamps :many
SELECT user_id, key, value, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetAllSettingsWithTimestamps(ctx context.Context, userID int64) ([]UserSetting, error) {
	rows, err := q.db.Query(ctx, getAllSettingsWithTimestamps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSetting{}
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM user_settings WHERE user_id = $1 AND key = $2
`

type GetSettingParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO user_settings (user_id, key, value, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at
`

type UpsertSettingParams struct {
	UserID    int64              `json:"user_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.UserID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const upsertSettingIfNewer = `-- name: UpsertSettingIfNewer :exec
INSERT INTO user_settings (user_id, key, value, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > user_settings.updated_at
`

type UpsertSettingIfNewerParams struct {
	UserID    int64              `json:"user_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSettingIfNewer(ctx context.Context, arg UpsertSettingIfNewerParams) error {
	_, err := q.db.Exec(ctx, upsertSettingIfNewer,
		arg.UserID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
