// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllSubscriptions = `-- name: CountAllSubscriptions :one
SELECT COUNT(*) FROM subscriptions
`

func (q *Queries) CountAllSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID                  int64              `json:"user_id"`
	PlanID                  int64              `json:"plan_id"`
	NextPlanID              pgtype.Int8        `json:"next_plan_id"`
	Status                  string             `json:"status"`
	Recurring               bool               `json:"recurring"`
	CurrentPeriodStart      pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd        pgtype.Timestamptz `json:"current_period_end"`
	YookassaPaymentMethodID pgtype.Text        `json:"yookassa_payment_method_id"`
	CreemCustomerID         pgtype.Text        `json:"creem_customer_id"`
	CreemSubscriptionID     pgtype.Text        `json:"creem_subscription_id"`
}

type CreateSubscriptionRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.NextPlanID,
		arg.Status,
		arg.Recurring,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.YookassaPaymentMethodID,
		arg.CreemCustomerID,
		arg.CreemSubscriptionID,
	)
	var i CreateSubscriptionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getActiveSubscriptionByUserID = `-- name: GetActiveSubscriptionByUserID :one
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE user_id = $1 AND status IN ('active', 'cancelled') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByUserID(ctx context.Context, userID int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.NextPlanID,
		&i.Status,
		&i.Recurring,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.YookassaPaymentMethodID,
		&i.CreemCustomerID,
		&i.CreemSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpiredSubscriptions = `-- name: GetExpiredSubscriptions :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE status IN ('active', 'cancelled') AND current_period_end < NOW()
`

func (q *Queries) GetExpiredSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getExpiredSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiringSubscriptions = `-- name: GetExpiringSubscriptions :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE status = 'active' AND recurring = TRUE AND current_period_end <= $1
`

func (q *Queries) GetExpiringSubscriptions(ctx context.Context, currentPeriodEnd pgtype.Timestamptz) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getExpiringSubscriptions, currentPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSubscriptionByUserID = `-- name: GetPendingSubscriptionByUserID :one
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE user_id = $1 AND status = 'pending' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPendingSubscriptionByUserID(ctx context.Context, userID int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getPendingSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.NextPlanID,
		&i.Status,
		&i.Recurring,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.YookassaPaymentMethodID,
		&i.CreemCustomerID,
		&i.CreemSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByCreemID = `-- name: GetSubscriptionByCreemID :one
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE creem_subscription_id = $1
`

func (q *Queries) GetSubscriptionByCreemID(ctx context.Context, creemSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCreemID, creemSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.NextPlanID,
		&i.Status,
		&i.Recurring,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.YookassaPaymentMethodID,
		&i.CreemCustomerID,
		&i.CreemSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.NextPlanID,
		&i.Status,
		&i.Recurring,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.YookassaPaymentMethodID,
		&i.CreemCustomerID,
		&i.CreemSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionsForRenewalReminder = `-- name: GetSubscriptionsForRenewalReminder :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE status = 'active' AND recurring = TRUE AND current_period_end >= $1 AND current_period_end < $2
`

type GetSubscriptionsForRenewalReminderParams struct {
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CurrentPeriodEnd_2 pgtype.Timestamptz `json:"current_period_end_2"`
}

func (q *Queries) GetSubscriptionsForRenewalReminder(ctx context.Context, arg GetSubscriptionsForRenewalReminderParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsForRenewalReminder, arg.CurrentPeriodEnd, arg.CurrentPeriodEnd_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsWithPendingPlanChange = `-- name: GetSubscriptionsWithPendingPlanChange :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE next_plan_id IS NOT NULL AND current_period_end < NOW()
`

func (q *Queries) GetSubscriptionsWithPendingPlanChange(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsWithPendingPlanChange)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllSubscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUserID = `-- name: ListSubscriptionsByUserID :many
SELECT id, user_id, plan_id, next_plan_id, status, recurring, current_period_start, current_period_end, yookassa_payment_method_id, creem_customer_id, creem_subscription_id, created_at, updated_at
FROM subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByUserID(ctx context.Context, userID int64) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.NextPlanID,
			&i.Status,
			&i.Recurring,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.YookassaPaymentMethodID,
			&i.CreemCustomerID,
			&i.CreemSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions SET plan_id = $2, next_plan_id = $3, status = $4, recurring = $5, current_period_start = $6, current_period_end = $7, yookassa_payment_method_id = $8, creem_customer_id = $9, creem_subscription_id = $10, updated_at = NOW()
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID                      int64              `json:"id"`
	PlanID                  int64              `json:"plan_id"`
	NextPlanID              pgtype.Int8        `json:"next_plan_id"`
	Status                  string             `json:"status"`
	Recurring               bool               `json:"recurring"`
	CurrentPeriodStart      pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd        pgtype.Timestamptz `json:"current_period_end"`
	YookassaPaymentMethodID pgtype.Text        `json:"yookassa_payment_method_id"`
	CreemCustomerID         pgtype.Text        `json:"creem_customer_id"`
	CreemSubscriptionID     pgtype.Text        `json:"creem_subscription_id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.PlanID,
		arg.NextPlanID,
		arg.Status,
		arg.Recurring,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.YookassaPaymentMethodID,
		arg.CreemCustomerID,
		arg.CreemSubscriptionID,
	)
	return err
}
