// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tls_certs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTLSCertByDomain = `-- name: DeleteTLSCertByDomain :exec
DELETE FROM tls_certificates WHERE domain = $1
`

func (q *Queries) DeleteTLSCertByDomain(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, deleteTLSCertByDomain, domain)
	return err
}

const getTLSCertByDomain = `-- name: GetTLSCertByDomain :one
SELECT id, domain, cert_pem, key_pem, expires_at, issued_at, created_at
FROM tls_certificates WHERE domain = $1
`

func (q *Queries) GetTLSCertByDomain(ctx context.Context, domain string) (TlsCertificate, error) {
	row := q.db.QueryRow(ctx, getTLSCertByDomain, domain)
	var i TlsCertificate
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CertPem,
		&i.KeyPem,
		&i.ExpiresAt,
		&i.IssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiringTLSCerts = `-- name: ListExpiringTLSCerts :many
SELECT id, domain, cert_pem, key_pem, expires_at, issued_at, created_at
FROM tls_certificates WHERE expires_at < $1
`

func (q *Queries) ListExpiringTLSCerts(ctx context.Context, expiresAt pgtype.Timestamptz) ([]TlsCertificate, error) {
	rows, err := q.db.Query(ctx, listExpiringTLSCerts, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TlsCertificate{}
	for rows.Next() {
		var i TlsCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CertPem,
			&i.KeyPem,
			&i.ExpiresAt,
			&i.IssuedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTLSCertificate = `-- name: UpsertTLSCertificate :one
INSERT INTO tls_certificates (domain, cert_pem, key_pem, expires_at, issued_at, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (domain) DO UPDATE SET
    cert_pem = EXCLUDED.cert_pem,
    key_pem = EXCLUDED.key_pem,
    expires_at = EXCLUDED.expires_at,
    issued_at = EXCLUDED.issued_at
RETURNING id
`

type UpsertTLSCertificateParams struct {
	Domain    string             `json:"domain"`
	CertPem   []byte             `json:"cert_pem"`
	KeyPem    []byte             `json:"key_pem"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) UpsertTLSCertificate(ctx context.Context, arg UpsertTLSCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTLSCertificate,
		arg.Domain,
		arg.CertPem,
		arg.KeyPem,
		arg.ExpiresAt,
		arg.IssuedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
