// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokensByUserID = `-- name: CountAPITokensByUserID :one
SELECT COUNT(*) FROM api_tokens WHERE user_id = $1
`

func (q *Queries) CountAPITokensByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokensByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, token_hash, name, allowed_subdomains, max_tunnels, allowed_ips, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, created_at
`

type CreateAPITokenParams struct {
	UserID            int64           `json:"user_id"`
	TokenHash         string          `json:"token_hash"`
	Name              string          `json:"name"`
	AllowedSubdomains json.RawMessage `json:"allowed_subdomains"`
	MaxTunnels        int32           `json:"max_tunnels"`
	AllowedIps        json.RawMessage `json:"allowed_ips"`
}

type CreateAPITokenRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.TokenHash,
		arg.Name,
		arg.AllowedSubdomains,
		arg.MaxTunnels,
		arg.AllowedIps,
	)
	var i CreateAPITokenRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const deleteAPITokensByUserID = `-- name: DeleteAPITokensByUserID :exec
DELETE FROM api_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAPITokensByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAPITokensByUserID, userID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, token_hash, name, allowed_subdomains, max_tunnels, allowed_ips, last_used_at, created_at
FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.AllowedSubdomains,
		&i.MaxTunnels,
		&i.AllowedIps,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT id, user_id, token_hash, name, allowed_subdomains, max_tunnels, allowed_ips, last_used_at, created_at
FROM api_tokens WHERE id = $1
`

func (q *Queries) GetAPITokenByID(ctx context.Context, id int64) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.AllowedSubdomains,
		&i.MaxTunnels,
		&i.AllowedIps,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByUserID = `-- name: ListAPITokensByUserID :many
SELECT id, user_id, token_hash, name, allowed_subdomains, max_tunnels, allowed_ips, last_used_at, created_at
FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUserID(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Name,
			&i.AllowedSubdomains,
			&i.MaxTunnels,
			&i.AllowedIps,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}
