// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTOTPSecret = `-- name: CreateTOTPSecret :one
INSERT INTO totp_secrets (user_id, secret_encrypted, is_enabled, backup_codes, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, created_at
`

type CreateTOTPSecretParams struct {
	UserID          int64  `json:"user_id"`
	SecretEncrypted string `json:"secret_encrypted"`
	IsEnabled       bool   `json:"is_enabled"`
	BackupCodes     []byte `json:"backup_codes"`
}

type CreateTOTPSecretRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTOTPSecret(ctx context.Context, arg CreateTOTPSecretParams) (CreateTOTPSecretRow, error) {
	row := q.db.QueryRow(ctx, createTOTPSecret,
		arg.UserID,
		arg.SecretEncrypted,
		arg.IsEnabled,
		arg.BackupCodes,
	)
	var i CreateTOTPSecretRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteTOTP = `-- name: DeleteTOTP :exec
DELETE FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteTOTP, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE totp_secrets SET is_enabled = FALSE WHERE user_id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, disableTOTP, userID)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE totp_secrets SET is_enabled = TRUE WHERE user_id = $1
`

func (q *Queries) EnableTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, enableTOTP, userID)
	return err
}

const getTOTPByUserID = `-- name: GetTOTPByUserID :one
SELECT id, user_id, secret_encrypted, is_enabled, backup_codes, created_at
FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) GetTOTPByUserID(ctx context.Context, userID int64) (TotpSecret, error) {
	row := q.db.QueryRow(ctx, getTOTPByUserID, userID)
	var i TotpSecret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretEncrypted,
		&i.IsEnabled,
		&i.BackupCodes,
		&i.CreatedAt,
	)
	return i, err
}

const isTOTPEnabled = `-- name: IsTOTPEnabled :one
SELECT is_enabled FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) IsTOTPEnabled(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isTOTPEnabled, userID)
	var is_enabled bool
	err := row.Scan(&is_enabled)
	return is_enabled, err
}

const updateTOTPBackupCodes = `-- name: UpdateTOTPBackupCodes :exec
UPDATE totp_secrets SET backup_codes = $2 WHERE user_id = $1
`

type UpdateTOTPBackupCodesParams struct {
	UserID      int64  `json:"user_id"`
	BackupCodes []byte `json:"backup_codes"`
}

func (q *Queries) UpdateTOTPBackupCodes(ctx context.Context, arg UpdateTOTPBackupCodesParams) error {
	_, err := q.db.Exec(ctx, updateTOTPBackupCodes, arg.UserID, arg.BackupCodes)
	return err
}

const updateTOTPSecret = `-- name: UpdateTOTPSecret :exec
UPDATE totp_secrets SET secret_encrypted = $2, is_enabled = $3, backup_codes = $4 WHERE id = $1
`

type UpdateTOTPSecretParams struct {
	ID              int64  `json:"id"`
	SecretEncrypted string `json:"secret_encrypted"`
	IsEnabled       bool   `json:"is_enabled"`
	BackupCodes     []byte `json:"backup_codes"`
}

func (q *Queries) UpdateTOTPSecret(ctx context.Context, arg UpdateTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, updateTOTPSecret,
		arg.ID,
		arg.SecretEncrypted,
		arg.IsEnabled,
		arg.BackupCodes,
	)
	return err
}
