// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersFiltered = `-- name: CountUsersFiltered :one
SELECT COUNT(*)
FROM users
WHERE ($1::boolean IS NULL OR is_active = $1)
  AND ($2::boolean IS NULL OR is_admin = $2)
  AND ($3::text IS NULL OR
       LOWER(email) LIKE $3 ESCAPE '\' OR
       LOWER(phone) LIKE $3 ESCAPE '\' OR
       LOWER(display_name) LIKE $3 ESCAPE '\')
`

type CountUsersFilteredParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	IsAdmin  pgtype.Bool `json:"is_admin"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersFiltered, arg.IsActive, arg.IsAdmin, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (phone, password_hash, display_name, is_admin, is_active, github_id, google_id, email, avatar_url, plan_id, created_at)
VALUES ($1, '', $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, created_at
`

type CreateOAuthUserParams struct {
	Phone       pgtype.Text `json:"phone"`
	DisplayName pgtype.Text `json:"display_name"`
	IsAdmin     bool        `json:"is_admin"`
	IsActive    bool        `json:"is_active"`
	GithubID    pgtype.Int8 `json:"github_id"`
	GoogleID    pgtype.Text `json:"google_id"`
	Email       pgtype.Text `json:"email"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	PlanID      pgtype.Int8 `json:"plan_id"`
}

type CreateOAuthUserRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (CreateOAuthUserRow, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.Phone,
		arg.DisplayName,
		arg.IsAdmin,
		arg.IsActive,
		arg.GithubID,
		arg.GoogleID,
		arg.Email,
		arg.AvatarUrl,
		arg.PlanID,
	)
	var i CreateOAuthUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, password_hash, display_name, is_admin, is_active, plan_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, created_at
`

type CreateUserParams struct {
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	IsAdmin      bool        `json:"is_admin"`
	IsActive     bool        `json:"is_active"`
	PlanID       pgtype.Int8 `json:"plan_id"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsAdmin,
		arg.IsActive,
		arg.PlanID,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.GithubID,
		&i.Email,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.PlanID,
		&i.FirstTunnelAt,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.GithubID,
		&i.Email,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.PlanID,
		&i.FirstTunnelAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.GithubID,
		&i.Email,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.PlanID,
		&i.FirstTunnelAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.GithubID,
		&i.Email,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.PlanID,
		&i.FirstTunnelAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.GithubID,
		&i.Email,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.PlanID,
		&i.FirstTunnelAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE is_active = TRUE) AS active,
    COUNT(*) FILTER (WHERE is_active = FALSE) AS blocked,
    COUNT(*) FILTER (WHERE is_admin = TRUE) AS admins
FROM users
WHERE ($1::text IS NULL OR
       LOWER(email) LIKE $1 ESCAPE '\' OR
       LOWER(phone) LIKE $1 ESCAPE '\' OR
       LOWER(display_name) LIKE $1 ESCAPE '\')
`

type GetUserStatsRow struct {
	Total   int64 `json:"total"`
	Active  int64 `json:"active"`
	Blocked int64 `json:"blocked"`
	Admins  int64 `json:"admins"`
}

func (q *Queries) GetUserStats(ctx context.Context, search pgtype.Text) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, search)
	var i GetUserStatsRow
	err := row.Scan(
		&i.Total,
		&i.Active,
		&i.Blocked,
		&i.Admins,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.PasswordHash,
			&i.DisplayName,
			&i.IsAdmin,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.GithubID,
			&i.Email,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.PlanID,
			&i.FirstTunnelAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkGitHub = `-- name: LinkGitHub :exec
UPDATE users SET github_id = $2,
    email = COALESCE(NULLIF(email, ''), $3),
    avatar_url = COALESCE(NULLIF(avatar_url, ''), $4)
WHERE id = $1
`

type LinkGitHubParams struct {
	ID        int64       `json:"id"`
	GithubID  pgtype.Int8 `json:"github_id"`
	Email     pgtype.Text `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) LinkGitHub(ctx context.Context, arg LinkGitHubParams) error {
	_, err := q.db.Exec(ctx, linkGitHub,
		arg.ID,
		arg.GithubID,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const linkGoogle = `-- name: LinkGoogle :exec
UPDATE users SET google_id = $2,
    email = COALESCE(NULLIF(email, ''), $3),
    avatar_url = COALESCE(NULLIF(avatar_url, ''), $4)
WHERE id = $1
`

type LinkGoogleParams struct {
	ID        int64       `json:"id"`
	GoogleID  pgtype.Text `json:"google_id"`
	Email     pgtype.Text `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) LinkGoogle(ctx context.Context, arg LinkGoogleParams) error {
	_, err := q.db.Exec(ctx, linkGoogle,
		arg.ID,
		arg.GoogleID,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const listUsersFiltered = `-- name: ListUsersFiltered :many
SELECT id, phone, password_hash, display_name, is_admin, is_active, created_at, last_login_at, github_id, email, avatar_url, google_id, plan_id, first_tunnel_at
FROM users
WHERE ($3::boolean IS NULL OR is_active = $3)
  AND ($4::boolean IS NULL OR is_admin = $4)
  AND ($5::text IS NULL OR
       LOWER(email) LIKE $5 ESCAPE '\' OR
       LOWER(phone) LIKE $5 ESCAPE '\' OR
       LOWER(display_name) LIKE $5 ESCAPE '\')
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersFilteredParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	IsActive pgtype.Bool `json:"is_active"`
	IsAdmin  pgtype.Bool `json:"is_admin"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) ListUsersFiltered(ctx context.Context, arg ListUsersFilteredParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersFiltered,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
		arg.IsAdmin,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.PasswordHash,
			&i.DisplayName,
			&i.IsAdmin,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.GithubID,
			&i.Email,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.PlanID,
			&i.FirstTunnelAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFirstTunnelAt = `-- name: SetFirstTunnelAt :execrows
UPDATE users SET first_tunnel_at = $2 WHERE id = $1 AND first_tunnel_at IS NULL
`

type SetFirstTunnelAtParams struct {
	ID            int64              `json:"id"`
	FirstTunnelAt pgtype.Timestamptz `json:"first_tunnel_at"`
}

func (q *Queries) SetFirstTunnelAt(ctx context.Context, arg SetFirstTunnelAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFirstTunnelAt, arg.ID, arg.FirstTunnelAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET display_name = $2, is_admin = $3, is_active = $4, last_login_at = $5, plan_id = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID          int64              `json:"id"`
	DisplayName pgtype.Text        `json:"display_name"`
	IsAdmin     bool               `json:"is_admin"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	PlanID      pgtype.Int8        `json:"plan_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.IsAdmin,
		arg.IsActive,
		arg.LastLoginAt,
		arg.PlanID,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    int64       `json:"id"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users SET phone = $2 WHERE id = $1
`

type UpdateUserPhoneParams struct {
	ID    int64       `json:"id"`
	Phone pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.Phone)
	return err
}

const updateUserPlan = `-- name: UpdateUserPlan :exec
UPDATE users SET plan_id = $2 WHERE id = $1
`

type UpdateUserPlanParams struct {
	ID     int64       `json:"id"`
	PlanID pgtype.Int8 `json:"plan_id"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error {
	_, err := q.db.Exec(ctx, updateUserPlan, arg.ID, arg.PlanID)
	return err
}
