run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    # Ignore certain linters in test files
    - path: _test\.go
      linters:
        - errcheck
    # Ignore unused in GUI bindings (used by Wails)
    - path: internal/gui/
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
