run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - bodyclose
    - gosec

issues:
  exclude-dirs:
    - gui
  exclude-rules:
    # Ignore unused in GUI bindings (used by Wails)
    - path: internal/gui/
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
