name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: fxTunnel version
      description: Output of `fxtunnel --version` or `fxtunnel-server --version`
      placeholder: "v3.2.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Server
        - CLI Client
        - GUI Client
        - Web UI
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: |
        When I run `fxtunnel http 3000`, the connection drops after ~30 seconds.
        Expected: connection stays open until I stop it.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Start server with default config
        2. Connect client: `fxtunnel http 3000 --server ...`
        3. Wait 30 seconds
        4. Connection drops
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (server or client). Use `--debug` flag for verbose logs.
      render: text
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your config (remove secrets!)
      render: yaml
    validations:
      required: false
