name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of fxTunnel does this relate to?
      options:
        - Server
        - CLI Client
        - GUI Client
        - Web UI
        - Protocol
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why do you need it?
      placeholder: "I often need to ... but currently I have to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've considered?
    validations:
      required: false
