package core

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"math/big"
	"net"
	"testing"
	"time"
)

func testControlCert(t *testing.T) tls.Certificate {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := x509.Certificate{
		SerialNumber: big.NewInt(1),
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
	}
	der, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	return tls.Certificate{Certificate: [][]byte{der}, PrivateKey: key}
}

// The control plane speaks exactly TLS 1.2 — no higher — so the server can
// never be the side that raises a session to 1.3, which some networks refuse to
// carry. Clients that still OFFER 1.3 lose their session regardless; see
// chromeSpecTLS12 for the cap that actually helps.
func TestControlTLSConfig_RejectsTLS13(t *testing.T) {
	l, err := listenSessionTLS("127.0.0.1:0", controlTLSConfig(testControlCert(t)))
	if err != nil {
		t.Fatal(err)
	}
	defer l.Close()
	go func() {
		for {
			conn, err := l.Accept()
			if err != nil {
				return
			}
			go func(c net.Conn) {
				_ = c.(*tls.Conn).Handshake()
				c.Close()
			}(conn)
		}
	}()

	t.Run("TLS 1.3 only client is refused", func(t *testing.T) {
		conn, err := tls.Dial("tcp", l.Addr().String(), &tls.Config{
			InsecureSkipVerify: true, //nolint:gosec // self-signed cert generated by the test
			MinVersion:         tls.VersionTLS13,
		})
		if err == nil {
			conn.Close()
			t.Fatal("server accepted a TLS 1.3 handshake, want refusal")
		}
	})

	t.Run("TLS 1.2 client succeeds", func(t *testing.T) {
		conn, err := tls.Dial("tcp", l.Addr().String(), &tls.Config{
			InsecureSkipVerify: true, //nolint:gosec // self-signed cert generated by the test
			MinVersion:         tls.VersionTLS12,
			MaxVersion:         tls.VersionTLS12,
		})
		if err != nil {
			t.Fatalf("TLS 1.2 handshake: %v", err)
		}
		defer conn.Close()
		if got := conn.ConnectionState().Version; got != tls.VersionTLS12 {
			t.Fatalf("negotiated %#04x, want TLS 1.2 (%#04x)", got, tls.VersionTLS12)
		}
	})
}
