// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function Clear(arg1:string):Promise<void>;

export function Get(arg1:string,arg2:string):Promise<gui.CapturedExchange>;

export function List(arg1:string,arg2:number,arg3:number):Promise<gui.ExchangeListResponse>;

export function Replay(arg1:string,arg2:string,arg3:gui.ReplayModifications):Promise<gui.ReplayResponse>;

export function Subscribe(arg1:string):Promise<void>;

export function Unsubscribe(arg1:string):Promise<void>;
