// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear(arg1) {
  return window['go']['gui']['InspectService']['Clear'](arg1);
}

export function Get(arg1, arg2) {
  return window['go']['gui']['InspectService']['Get'](arg1, arg2);
}

export function List(arg1, arg2, arg3) {
  return window['go']['gui']['InspectService']['List'](arg1, arg2, arg3);
}

export function Subscribe(arg1) {
  return window['go']['gui']['InspectService']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['gui']['InspectService']['Unsubscribe'](arg1);
}
